### PR TITLE
Use Minetweaker3 via ivy build artifact rather than copied .java files.

### PR DESCRIPTION
**Pull request by kylev**
This uses an [ivy artifact](http://gradle.org/docs/current/dsl/org.gradle.api.artifacts.repositories.IvyArtifactRepository.html) instead of checking in large amounts of .java files from other people's projects. It makes upgrading to a new version of Minetweaker super easy (just a line in `build.properties`).

I can't fully test this, since AgriCraft has a bunch of unstated dependencies that it seems like are only set up on your machines rather than in the Gradle build specification (I'll probably fix some of that as well, soon).

The 12,600 lines removed are just `src/api/java/minetweaker/*`. There are no modifications to AgriCraft source code, and just a few lines of changes to build scripts.

### CODE REVIEW

**Comment by InfinityRaider** [comment]
Thanks, but I'll wait with merging this, I'll test it out in a seperate branch and then merge it into master.

btw @Imasius has set up a dropbox with dependencies.

**Comment by kylev** [comment]
Cool. It looks like a *lot* of mod developers need both (1) help setting up maven sources and (2) help publishing maven artifacts.

Notably, Pam's Harvestcraft is really hard to use via standard build tools. So I'm going to reach out to other mod writers and see if I can get them up and running with maven repos/hosting/instructions to make extending and using other mods easier and more fun.

I'll rebase this to fix the conflict, too.

**Comment by kylev** [comment]
Rebased and back to clean merge-able state.

**Comment by InfinityRaider** [comment]
Thanks man, if i'd know how to decently work with Maven and/or Gradle I'd do it myself.

**Comment by kylev** [comment]
My pleasure! Let me know if you have any problems with your dev environment now. I want to propagate good software practices and reliable Gradle build tooling examples around the modding community, and really appreciate that you're receptive to my tweaks.

Hopefully I'll be able to get things to the point where everyone can get up and running in helping debug/improve mods with just a few short commands and no magic! Well, except for the mods that implement the magic...

**Comment by InfinityRaider** [comment]
I haven't set my dev environment up all over again, but if it works on your end it will work on anyone's end I suppose.

**Pull request merged**
