### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by RlonRyan**
I won't be so eager to merge this one... lol... sorry.

### CODE REVIEW

**Comment by RlonRyan** [comment]
Sorry if NetBeans went a little bit overboard on correcting the names in the comments.

**Comment by RlonRyan** [comment]
Also, could you please do me a favor and run an optimize imports for me, please?

**Comment by RlonRyan** [comment]
They are a side effect of changing the item names to lowercase, as to match the 1.8 convention.

**Comment by InfinityRaider** [comment]
Ah okay then.

**Comment by RlonRyan** [comment]
I think that is all I will do for today...

**Pull request merged**
