### PR TITLE
Separate MultiBlocks from Tanks

### PR DESCRIPTION
**Pull request by RlonRyan**
Hopefully this will make the tanks more manageable.

### CODE REVIEW

**Comment by RlonRyan** [comment]
Man this is quite the task...

**Comment by RlonRyan** [comment]
This multi-block stuff doesn't seem to want to behave as it should...

**Comment by RlonRyan** [comment]
The problem is that I would like all the multiblocks to point to a single controller, but there is no good way to save the pointer to that controller, meaning that the controller would have to be reconstructed on load, an inefficient proposition.

**Comment by InfinityRaider** [comment]
Can you make this PR on the tank branch please?

**Comment by RlonRyan** [comment]
Will do.

**Comment by RlonRyan** [comment]
Yeah, this does need some co-op work.

**Comment by RlonRyan** [comment]
Sorry for taking so long just finishing up a few more tweaks...

**Comment by RlonRyan** [comment]
Ok. About to commit... The only thing I can't perfect is the multiblock breaking as it seems to get called too many times.

**Pull request closed without merging**
