### PR TITLE
New Textures for the tools

### PR DESCRIPTION
**Pull request by MechWarrior99**
The textures you have now look, well... they are not exactly pleasing to the eye, at least for a lot of people. And some one asked me to make some new textures for it so i did :)

Old textures:

New textures:

### CODE REVIEW

**Comment by Yulife** [comment]
Wow... those look stunning! :scream:

**Comment by MechWarrior99** [comment]
Thank you! A guy named Inap gave be feed back on them so i could change them a bit and make them look how they do now :)

**Comment by BBoldt** [comment]
These look great!

**Comment by InfinityRaider** [comment]
Awesome, cheers

**Pull request merged**
