### PR TITLE
Update zh_CN.lang

### PR DESCRIPTION
**Pull request by GWYOG**
After discussing with @claybiockiller, I update the .lang file, fix some typos and revise some of the former translations.

### CODE REVIEW

**Comment by claybiockiller** [comment]
Dear GWYOG,
Sorry.
First,The English phrase "Water chestnut" can mean both Trapa natans(菱角) or Eleocharis dulcis(荸荠). Which is referred in Pam's?
Second,my last edition of translation is focused more on external unity than internal.It's a dillemma.
尊敬的GWYOG,
抱歉。
首先，英文中 "Water chestnut" 这一短语可指代菱角（拉丁学名Trapa natans）或荸荠（拉丁学名Eleocharis dulcis）。潘马斯中为何种作物？
其次，我的上一版本汉化更重视外部统一而非内部统一。这是个矛盾。

Claybiockiller(Github)/Clayblockiller(MCF)/Clayblock(MCBBS)

**Comment by GWYOG** [comment]
@claybiockiller, I assume that we'd better not to discuss the details of the translation here, so I PM you on MCBBS, please check it out.

Sorry for the inconsistency, we will revise the translation after a further discussion.

**Comment by InfinityRaider** [comment]
So do I merge this or wait for a revised PR?

**Comment by GWYOG** [comment]
Actually, there are few things need to be revised, such as the translation of "Water chestnut" from Pam's Harvestcraft. There is no official translation of it. Even worse, there exists two different unofficial Chinese translations of it, and I just follow the one from an open PR of Pam's Harvestcraft's repository. 

Sorry, I haven't got in touch with @claybiockiller till now. So it perhaps will need some time for us to discuss about the accurate translation of it. But I promise it wouldn't take a long time.

Will the revised version remain in this open PR(#539) if I PR it later? If it will, please waiting for me to update the revised one later. If it won't, and will open another PR, I think it's OK to merge this one. I promise that most of the translations here are accurate.

**Comment by InfinityRaider** [comment]
Ill keep this open, just add the revised version to this PR and I'll merge afterwards.

**Comment by GWYOG** [comment]
Got it.

**Comment by GWYOG** [comment]
Revision has been done, I think it can be merged now. =D

**Pull request merged**
