### PR TITLE
Continued Updates

### PR DESCRIPTION
**Pull request by RlonRyan**
Attempted to improve code more.

### CODE REVIEW

**Comment by RlonRyan** [comment]
I still have no idea why the CustomWood blocks are suddenly undifferentiated in 1.8...

**Comment by RlonRyan** [comment]
The other thing is, if we ever wanted to rewrite the api, this would be the time.

**Comment by RlonRyan** [comment]
Should we completely remove the travis automation stuff?

**Comment by RlonRyan** [comment]
Also, why isn't the AgriCraft icon on CurseForge the normal one?
It kinda bugs me...

**Comment by InfinityRaider** [comment]
Idk, what do you mean with AgriCraft icon?
Also what is up with all those reordering of imports?

**Comment by RlonRyan** [comment]
The Wheat and Hoe icon... (At least I was under the impression that was the agricraft icon, it is after all on the creative tab and mod info page...)

I can undo the import reorder commit, I was just trying to remove all the unused imports and clean up a bit...

**Comment by InfinityRaider** [comment]
I don't mind that, the only proble is that when I run an optimize imports it'll shuffle it again, and then when you do it again it'll be shuffled again and it'll uglify the commits.

**Comment by RlonRyan** [comment]
Ah. I see, want me to try to remove the commit then?

**Comment by InfinityRaider** [comment]
Would be appreciated.

**Comment by RlonRyan** [comment]
Will do.

**Comment by RlonRyan** [comment]
I still think that an optimize imports is needed. It seemed to remove some build hiccups...

**Comment by RlonRyan** [comment]
We need to switch the root classes to interfaces...

**Comment by InfinityRaider** [comment]
Why exactly?

**Comment by RlonRyan** [comment]
Ok, maybye not...

**Comment by RlonRyan** [comment]
It's just that the seeds, which are items do not extend the agricraft item class...

**Comment by RlonRyan** [comment]
Btw: I updated the icon... :hint:

**Comment by InfinityRaider** [comment]
I did that deliberately to keep the vanilla ItemSeeds implementation, in case some mods check for ItemSeeds. About the icon, I know I saw, but I don't think some mods use the same naming for their items and icons like vanilla does.

**Comment by RlonRyan** [comment]
Yeah I figured we needed to keep the seeds subclasses of ItemSeeds, it just complicates the internal class structure, which is why I thought an interface might work better. However, it might be better for us not to consider seeds items, and rather a subclass of ItemSeeds...

**Comment by RlonRyan** [comment]
Oh and the Icon was the .png for the CurseForge... I don't know what you are talking about for the naming though, are you referring to SafeIcon?

**Comment by InfinityRaider** [comment]
Yes

**Comment by RlonRyan** [comment]
Yeah that's more for internal loading, and might be temporary...

**Pull request merged**
