### PR TITLE
Initial creating zh_CN.lang

### PR DESCRIPTION
**Pull request by 3TUSK**
Here is the Simplified Chinese localization file

### CODE REVIEW

**Comment by InfinityRaider** [comment]
Can you make this pull request to the 1.3 branch please?

**Comment by InfinityRaider** [comment]
Nvm, I'll just cherrypick it, thanks.

**Comment by 3TUSK** [comment]
just in case, did I make something wrong...?

**Comment by InfinityRaider** [comment]
No, not at all, But I have a 1.3 branch where I fix bugs in the current alpha version, and I'd like to have your new lang files there as well. If I didn't put them on there, they'd be released when the next major version (1.4) us released.

**Comment by 3TUSK** [comment]
Thx very much

**Pull request merged**
