### PR TITLE
Refactor Patch

### PR DESCRIPTION
**Pull request by RlonRyan**
The goal of this branch is to rename everything to match both Minecraft and Java standards.

This required renaming the packages to lowercase, so it looks bigger than it is.

### CODE REVIEW

**Comment by RlonRyan** [comment]
Dangit! Git didn't commit the folder name changes.

**Comment by RlonRyan** [comment]
I'm going to have to re-branch this... This branch is a lost cause... Sorry.

**Comment by InfinityRaider** [comment]
Don't worry, (g)it happens

 (see what I did there?)

**Comment by RlonRyan** [comment]
lol

**Pull request closed without merging**
