### PR TITLE
Added Mutator Item

### PR DESCRIPTION
**Pull request by RlonRyan**
So seeds may be mutated in creative quickly.

### CODE REVIEW

**Comment by RlonRyan** [comment]
Just needs 2 more things:

1. Combining recipes. (Not crafting recipes).
2. Textures... (Beyond my skill).

**Comment by RlonRyan** [comment]
Well adding the recipes might be hard, as there are (3^3) * (n^3) possible items...

**Comment by InfinityRaider** [comment]
Thanks, but I deliberatly never added something like this to avoid cheating.

**Comment by RlonRyan** [comment]
I figured as much. Still, it was good practice for me, so not a total waste.

**Comment by InfinityRaider** [comment]
I'll merge it and play around with it, I'm going to hide it from NEI though, or I might only register it if a dev env is detected.

**Comment by RlonRyan** [comment]
Ok. Cool. Yeah, I agree to keep it away from non-creative as it would break the gameplay. It was more of a tool for the server admins who wanted to replace things that got lost for some reason.

**Comment by RlonRyan** [comment]
I think using the generic crop implementation, we might be able to cut out half of the api classes, and have the same functionality.

**Comment by RlonRyan** [comment]
Durp. Wrong java version number.

**Comment by InfinityRaider** [comment]
Can you make a different PR for this, and Unchange allt he changes to API methods?

**Comment by RlonRyan** [comment]
I'll make a personal branch for the last two commits then.

**Comment by InfinityRaider** [comment]
Can you make two different PR's when you find the time? One for the mutator and one for the formatting (without the change to the API methods).

**Pull request closed without merging**
