### PR TITLE
Master

### PR DESCRIPTION
**Pull request by RlonRyan**

### CODE REVIEW

**Comment by RlonRyan** [comment]
I see why other mods always have you click on the structure with some kind of tool. The onPlace() function is pretty useless as it is unreliable. I'm thinking our best option is having users right click with a hoe?

**Comment by InfinityRaider** [comment]
No, its working fine now, so Its possible to make it work without a tool.

**Comment by RlonRyan** [comment]
We can see. It's just the breaking and reforming can happen multiple times in the current implementation, leading to things like the created water issue.

**Comment by RlonRyan** [comment]
Wait do I get commit access to the branch, or do you want me to keep creating pull requests?

**Comment by InfinityRaider** [comment]
Can I give you commit access to one branch?

**Comment by RlonRyan** [comment]
I haven't the slightest idea. It seems like that should be a feature, although it probably isn't.

I'll keep making pull requests.

**Comment by RlonRyan** [comment]
I think I finally found why the multiblock tanks weren't responding to my breakMultiBlock() changes... the tank class overrode the method... lol!

**Comment by RlonRyan** [comment]
Ok. Just down to figuring out how to get the multiblock to form when a block is placed.

**Comment by RlonRyan** [comment]
This time I really think that I am down to one problem: How to set the destroy particle texture.

Any ideas?

**Pull request merged**
