### PR TITLE
Dev growth

### PR DESCRIPTION
**Pull request by InfinityRaider**
Pls review @RlonRyan

### CODE REVIEW

**Comment by RlonRyan** [comment]
I guess that this is fine. There is too much work put into it not to merge it.

**Comment by RlonRyan** [comment]
I'll go look at fixing AgriCore first, and then add that to this pr.

Also, we need to finish the change log for a4.

**Comment by RlonRyan** [comment]
You seem to have broken the item rendering... The items rendering now ignores nbts it would appear?

**Comment by RlonRyan** [comment]
I'd go ahead and merge this now.

**Comment by RlonRyan** [comment]
Something seems to have broken the seeds...

**Comment by InfinityRaider** [comment]
Ok merge is go

**Pull request merged**
