### PR TITLE
Added Annotation-Based Configuration

### PR DESCRIPTION
**Pull request by RlonRyan**
It allows for the placement of configurable values in the class that
they are actually used. It also allows for the cutting down on the
massive ConfigurationHandler class.

### CODE REVIEW

**Comment by RlonRyan** [comment]
I got a bit off-track on the render branch... lol.

**Comment by RlonRyan** [comment]
I didn't want to commit this to the render branch, in case if you didn't like it.

Personally, I think it's quite neat.

**Comment by RlonRyan** [comment]
Like I said, very far off track...

**Comment by InfinityRaider** [comment]
I like the annotation based config, I was planning on rewriting it to an interface-based system to make it exposed to the api, so people could read agricraft's config settings without having to do all-too crazy things

**Comment by InfinityRaider** [comment]
Just one concern, for ints the config needs a default and a range, for strings and booleans its just a default. And how do you plan to tackle arrays?

**Comment by RlonRyan** [comment]
The default is the value that is already assigbed to the field, and the range is already handled with min and max.

**Comment by RlonRyan** [comment]
Arrays will take a bit more work but should be doable.

**Comment by InfinityRaider** [comment]
Ah yes, you just give them a range, but the values doesn't actually do anything, I see.

**Comment by RlonRyan** [comment]
What values?

**Comment by InfinityRaider** [comment]
for min and max.

**Comment by RlonRyan** [comment]
Oh they are functional...

**Comment by RlonRyan** [comment]
I think that should do it for this branch, given that you are o.k. with it.

Give me the word, and I'll merge it back into dev-renderer...

**Comment by RlonRyan** [comment]
(I kinda want to add a `develop` label for these dev-branch prs...)

**Comment by RlonRyan** [comment]
So...

**Comment by InfinityRaider** [comment]
I couldve sworn I added that label...

**Comment by InfinityRaider** [comment]
Apparently I did

**Pull request merged**
