### PR TITLE
Chinese Localization Part 1.5

### PR DESCRIPTION
**Pull request by claybiockiller**

### CODE REVIEW

**Comment by 3TUSK** [comment]
Seriously, but why not squash into _only one_ commit?

**Comment by claybiockiller** [comment]
3T is everywhere......
Because I sometimes stop translation of Agricraft and check out related mod......
3T无处不在。。。。。。
因为我有时会暂时中断农业工艺汉化并查看联动模组。。。。。。
Claybiockiller(Github)/Clayblockiller(MCF)/Clayblock(MCBBS)

**Comment by liach** [comment]
@3TUSK Most localization contributors edits online and do not squash commit as they do not have a client.

**Comment by InfinityRaider** [comment]
Although single commits are cleaner I do not really mind, so it's fine guys.

**Comment by 3TUSK** [comment]
@liach I usually either copy the `en_US.lang` to local or execute `git clone` when I lose my mind, since I know I would pause somewhere. I always try making everything clean.

**Pull request merged**
