### PR TITLE
Render Branch

### PR DESCRIPTION
**Pull request by RlonRyan**
The goal of this branch is to simplify the rendering process.

### CODE REVIEW

**Comment by RlonRyan** [comment]
Redoing the crop renderer is going to require some serious refactoring.

**Comment by RlonRyan** [comment]
Other than that, the rendering seems pretty good now...

**Comment by RlonRyan** [comment]
I might need your help with hacking in the dropped item rendering...

**Comment by InfinityRaider** [comment]
What do you mean with dropped item rendering? doesn't it work anymore? It used to work.

**Comment by RlonRyan** [comment]
It works with the the items that use JSON, just not our custom items.
They just render as the default texture block.

**Comment by InfinityRaider** [comment]
Hmm, it worked in 1.8.8, I'll have a look at it.

**Comment by RlonRyan** [comment]
Ok, thanks.

**Comment by RlonRyan** [comment]
I don't know what you think about the state of this branch, but I think it might be good to go for a merge.

**Comment by InfinityRaider** [comment]
I'm alright with it, so you have a green light from me.

**Comment by RlonRyan** [comment]
Sounds good!

**Pull request merged**
