### PR TITLE
Master

### PR DESCRIPTION
**Pull request by RlonRyan**
Some improvements to the code, removing some of the magic numbers and spelling errors. 

This PR makes weeds customizable from the configuration files, similar to other crops.

### CODE REVIEW

**Comment by RlonRyan** [comment]
Very well, but perhaps a new api might be a good idea in the future.

**Comment by RlonRyan** [comment]
Well I had the thing fixed, then git decided to dump the commit... It was more of a few suggestions anyway.

**Comment by InfinityRaider** [comment]
I quickly went over your suggestions, and I agree with most of them. Thanks for your effort.
I am willing to merge almost all of them, except for the ones that change the API. Fertiliser is according to British spelling, while Fertilizer is the American one, and I prefer the British.

**Comment by RlonRyan** [comment]
Well then... Let's try this again...

*Dang British... Always misspelling things.*

**Pull request closed without merging**
