### PR TITLE
Minor Code Improvements

### PR DESCRIPTION
**Pull request by RlonRyan**
This is an attempt to simplify the core code.

### CODE REVIEW

**Comment by InfinityRaider** [comment]
Welcome back ;D

**Comment by RlonRyan** [comment]
Good to see you too!
Oh the .gitattributes is something my git client keeps adding to my projects.
It's just a way to normalize the way files are treated.

**Comment by InfinityRaider** [comment]
Well its no use to me or anyone else then I guess, so can you add it to .gitignore please?

**Comment by RlonRyan** [comment]
Will do.

**Comment by InfinityRaider** [comment]
Cheers.

**Comment by RlonRyan** [comment]
:tada:

**Comment by RlonRyan** [comment]
Ooh... That was PR number 100!

**Pull request merged**
