### PR TITLE
Huge Update

### PR DESCRIPTION
**Pull request by RlonRyan**
As per #363, but with the fixes wanted.

### CODE REVIEW

**Comment by RlonRyan** [comment]
I hope this looks good to you!

**Comment by RlonRyan** [comment]
What would you think about a connector channel?
Or what about trying to set the tank bounds based on the state?

**Comment by InfinityRaider** [comment]
Haven't merged it due to lack of time yesterday.
And what do you mean with setting the tank bounds based on the state?

**Comment by RlonRyan** [comment]
I mean somehow possibly setting the tank bounds so you could fall in? It might be a little too involved though...

**Comment by RlonRyan** [comment]
When do you think the next snapshot should come out? Its been almost a month since the last beta, and it might be a good idea to get some testers on the progress...

You could probably disable the seed storage for a single commit, and do a release...

**Comment by InfinityRaider** [comment]
Seed Storage Controllers will be delayed for a while, I just want to finish the Peripheral GUI and rendering before I do another release.

**Comment by RlonRyan** [comment]
Sounds good. Are we a go with the merge for now?

**Pull request merged**
