### PR TITLE
Continued Render Updates

### PR DESCRIPTION
**Pull request by RlonRyan**
This is a continuation of the render branch, which was previously merged as to preserve progress.

### CODE REVIEW

**Comment by RlonRyan** [comment]
I plan to remove the item rendering classes completely, now that we have an alternate way of rendering items... That is, so long as it is ok with you.

**Comment by InfinityRaider** [comment]
If it works, and it doesn't use that hack I'm totally fine with it.

**Comment by RlonRyan** [comment]
I just have to figure out how to correct the held item orientation...

**Comment by RlonRyan** [comment]
Well... I got it down to only having 60 model load failures...

**Comment by RlonRyan** [comment]
lol... WAILA for 1.8.9 still works on our blocks, but not a vanilla lever...

**Comment by RlonRyan** [comment]
Well, this is a dev branch after all, so we keep working on it until it gets to a state at which it is appropriate to merge.

**Comment by RlonRyan** [comment]
We should probably combine the seeds like the clippings...

Also, is there any reason that AgriCraftCrops have to be blocks? They are never used as actual blocks...

**Comment by RlonRyan** [comment]
Anyways, the clipping rendering seems pretty good now, although the plant icons on them are a *bit* too big... lol.

**Comment by InfinityRaider** [comment]
They can all be grown outside of crop sticks, idk they started of like that when the code was based on vanilla's implementation of crops and seeds. But then I'd have to start writing exceptions for some mods which don't follow vanilla's implementation. At a certain point there were so many exeptions that I decided to make my own interface for it and base everything on that.

**Comment by RlonRyan** [comment]
Well I guess if they need to be grown outside of crops that is fine... but not having them as blocks might simplify a lot of things...

**Comment by InfinityRaider** [comment]
Why is that? They are identical to wheat, just with other textures, so we can just copy the json for wheat and modify the texture name.

**Comment by RlonRyan** [comment]
As in we don't have to worry about registering blocks or loading JSON files for them...
And to have everything done through an interface would be pretty nice...

**Comment by InfinityRaider** [comment]
I don't understand the json thing yet, but when I do I'm sure itd be possible with Forge to have a single json and just use the appropriate textures. The textures are named very consistently anyways.

**Comment by RlonRyan** [comment]
Well that should cover any normal item models we need to generate...

**Comment by RlonRyan** [comment]
I think that this branch should be good for now.

**Pull request merged**
