### PR TITLE
Refactor Patch

### PR DESCRIPTION
**Pull request by RlonRyan**
The goal of this branch is to refactor all the AgriCraft code to match both MineCraft and Java standards.

### CODE REVIEW

**Comment by RlonRyan** [comment]
Ok... I think that time I got it done right!

**Comment by RlonRyan** [comment]
@InfinityRaider I did it! I found the line causing the custom wood blocks to act funny!

**Comment by InfinityRaider** [comment]
What line was it?

**Comment by RlonRyan** [comment]
The tile entity dummy was not reloading the icon every time the material changed.

**Comment by InfinityRaider** [comment]
ooooooh, good find.

**Comment by RlonRyan** [comment]
So do you think the package rename will be ok?

**Comment by InfinityRaider** [comment]
Its the first release, so sure.

**Comment by RlonRyan** [comment]
Cool.

**Comment by RlonRyan** [comment]
That last commit was quite the upgrade, if I do say so myself.

**Comment by RlonRyan** [comment]
So... I think this branch is good to go... I kinda got off track on the renderers...

Renderer work next.

**Comment by InfinityRaider** [comment]
I don't really have any comments/remarks for this so you're free to merge it, unless you want to add some more commits.

**Comment by RlonRyan** [comment]
Ok... sounds good...

Isn't it like 3AM for you?

**Pull request merged**
